# Generated by Django 3.0 on 2024-08-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def transfer_data(apps, schema_editor) -> None:
    old_profile = apps.get_model('oc_lettings_site', 'Profile')
    new_profile = apps.get_model('profiles', 'Profile')

    for old_obj in old_profile.objects.all():
        new_profile.objects.create(
            user=old_obj.user,
            favorite_city=old_obj.favorite_city,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lettings', '0001_initialize_and_transfer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(transfer_data),
    ]
