# Generated by Django 3.0 on 2024-08-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def transfer_data(apps, schema_editor) -> None:
    """This function is intended to be used in a Django migration to transfer Profile data
    from the old models in the oc_lettings_site app to the new models in the Profile app.

    Args:
        apps (Apps): An instance that gives access to the historical versions of models.
        schema_editor (SchemaEditor): The database schema editor responsible
            for applying the migration.

    Returns:
        None
    """
    old_profile = apps.get_model('oc_lettings_site', 'Profile')
    new_profile = apps.get_model('profiles', 'Profile')

    for old_obj in old_profile.objects.all():
        new_profile.objects.create(
            user=old_obj.user,
            favorite_city=old_obj.favorite_city,
        )


class Migration(migrations.Migration):
    """This migration creates the `Profile` model in the 'profiles' app, then runs
    a data transfer operation to move existing data from the old models in 'oc_lettings_site'
    to the newly created models.

    Attributes:
        initial (bool): Indicates whether this is an initial migration.
        dependencies (list): Specifies the migration dependencies.
            This migration depends on the initial migration of the 'lettings' app.
        operations (list): A list of operations to be performed in this migration.
            This includes creating the new models and running the
            `transfer_data` function to move the data.
    """

    initial = True

    dependencies = [
        ('lettings', '0001_initialize_and_transfer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                 ),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)
                 ),
            ],
        ),
        migrations.RunPython(transfer_data),
    ]
