# Generated by Django 3.0 on 2024-08-06 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def transfer_data(apps, schema_editor) -> None:
    """This function is intended to be used in a Django migration to transfer Address and Letting
    data from the old models in the oc_lettings_site app to the new models in the lettings app.

    Args:
        apps (Apps): An instance that gives access to the historical versions of models.
        schema_editor (SchemaEditor): The database schema editor responsible
            for applying the migration.

    Returns:
        None
    """
    old_address = apps.get_model('oc_lettings_site', 'Address')
    new_address = apps.get_model('lettings', 'Address')

    address_id_mapping = {}

    for old_obj in old_address.objects.all():
        new_obj = new_address.objects.create(
            number=old_obj.number,
            street=old_obj.street,
            city=old_obj.city,
            state=old_obj.state,
            zip_code=old_obj.zip_code,
            country_iso_code=old_obj.country_iso_code,
        )
        address_id_mapping[old_obj.id] = new_obj.id

    old_letting = apps.get_model('oc_lettings_site', 'Letting')
    new_letting = apps.get_model('lettings', 'Letting')

    for old_obj in old_letting.objects.all():
        new_address_id = address_id_mapping[old_obj.address_id]
        new_letting.objects.create(
            title=old_obj.title,
            address=new_address.objects.get(id=new_address_id),
        )


class Migration(migrations.Migration):
    """This migration creates the `Address` and `Letting` models in the 'lettings' app, then runs
    a data transfer operation to move existing data from the old models in 'oc_lettings_site'
    to the newly created models.

    Attributes:
        initial (bool): Indicates whether this is an initial migration.
        dependencies (list): Specifies the migration dependencies.
            This migration depends on the initial migration of the 'oc_lettings_site' app.
        operations (list): A list of operations to be performed in this migration.
            This includes creating the new models and running the
            `transfer_data` function to move the data.
    """

    initial = True

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                 ),
                ('number', models.PositiveIntegerField(
                    validators=[django.core.validators.MaxValueValidator(9999)])
                 ),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(
                    max_length=2, validators=[django.core.validators.MinLengthValidator(2)])
                 ),
                ('zip_code', models.PositiveIntegerField(
                    validators=[django.core.validators.MaxValueValidator(99999)])
                 ),
                ('country_iso_code', models.CharField(
                    max_length=3, validators=[django.core.validators.MinLengthValidator(3)])
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Letting',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                 ),
                ('title', models.CharField(max_length=256)),
                ('address', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='lettings.Address')
                 ),
            ],
        ),
        migrations.RunPython(transfer_data),
    ]
